# Generated by Django 5.2.4 on 2025-07-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='catagory',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
