# Generated by Django 5.2.4 on 2025-12-29 12:13

import versatileimagefield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecategory',
            name='icon',
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='service'),
        ),
    ]
