# Generated by Django 5.2.4 on 2025-07-24 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_works_catagory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faqs',
        ),
    ]
