# Generated by Django 5.2.4 on 2025-12-29 19:06

import django.db.models.deletion
import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_servicecategory_icon_alter_service_icon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkCategory',
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='web.servicecategory'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='service/icons'),
        ),
        migrations.AlterField(
            model_name='works',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='web.servicecategory'),
        ),
    ]
