# Generated by Django 5.2.4 on 2026-01-14 09:21

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_delete_workcategory_alter_service_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='detail_description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='included_items',
            field=tinymce.models.HTMLField(blank=True, help_text="HTML list or content for 'Includes this service' section", null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='sub_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='ServiceFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', tinymce.models.HTMLField()),
                ('order', models.PositiveIntegerField(default=1)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='web.service')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
