# Generated by Django 5.2.4 on 2026-01-14 09:46

import tinymce.models
import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_service_detail_description_service_included_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='counter_steps',
            field=tinymce.models.HTMLField(blank=True, help_text='Optional HTML to replace the 3 bottom counter-step cards.', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, help_text='Main image used on the service inner page (circle and gallery).', null=True, upload_to='service/images'),
        ),
        migrations.AddField(
            model_name='service',
            name='planning_list',
            field=tinymce.models.HTMLField(blank=True, help_text='Optional <li> elements for the planning bullet list.', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='process_description',
            field=tinymce.models.HTMLField(blank=True, help_text='Optional paragraph shown below the process images.', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='process_steps',
            field=tinymce.models.HTMLField(blank=True, help_text="Optional HTML to replace the 4-step 'Our process' cards.", null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='detail_description',
            field=tinymce.models.HTMLField(blank=True, help_text='Main detailed description text of the service.', null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='included_items',
            field=tinymce.models.HTMLField(blank=True, help_text="HTML list or content for the 'Includes this service' section.", null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='short_description',
            field=tinymce.models.HTMLField(blank=True, help_text='Short rich-text description shown under the subtitle.', null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='sub_title',
            field=models.CharField(blank=True, help_text='Subtitle shown near the top of the service inner page.', max_length=200, null=True),
        ),
    ]
