# Generated by Django 5.2.4 on 2026-01-14 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_servicecounterstep_serviceincludeditem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceincludeditem',
            name='service',
        ),
        migrations.RemoveField(
            model_name='serviceplanningitem',
            name='service',
        ),
        migrations.RemoveField(
            model_name='serviceprocessstep',
            name='service',
        ),
        migrations.DeleteModel(
            name='ServiceCounterStep',
        ),
        migrations.DeleteModel(
            name='ServiceIncludedItem',
        ),
        migrations.DeleteModel(
            name='ServicePlanningItem',
        ),
        migrations.DeleteModel(
            name='ServiceProcessStep',
        ),
    ]
