# Generated by Django 5.2.4 on 2026-01-15 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_remove_serviceincludeditem_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='counter_steps',
        ),
        migrations.RemoveField(
            model_name='service',
            name='detail_description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='included_items',
        ),
        migrations.RemoveField(
            model_name='service',
            name='planning_list',
        ),
        migrations.RemoveField(
            model_name='service',
            name='process_description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='process_steps',
        ),
        migrations.RemoveField(
            model_name='service',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='sub_title',
        ),
    ]
