# Generated by Django 5.2.4 on 2026-01-17 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_remove_service_counter_steps_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePlaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planing_list', to='web.service')),
            ],
        ),
    ]
