# Generated by Django 5.2.4 on 2026-01-17 05:49

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_serviceplaning'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceplaning',
            name='planing_list',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
    ]
