# Generated by Django 5.2.4 on 2026-01-17 05:56

import django.db.models.deletion
import tinymce.models
import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_serviceplaning_planing_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicefaq',
            options={},
        ),
        migrations.RemoveField(
            model_name='servicefaq',
            name='order',
        ),
        migrations.CreateModel(
            name='ServicePageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='service/images')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_images', to='web.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServicePlaningStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planing_title', models.CharField(max_length=100)),
                ('planing_description', tinymce.models.HTMLField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_steps', to='web.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_list', tinymce.models.HTMLField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_steps', to='web.service')),
            ],
        ),
        migrations.DeleteModel(
            name='ServicePlaning',
        ),
    ]
