# Generated by Django 5.2.4 on 2026-01-17 06:02

import versatileimagefield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_alter_servicefaq_options_remove_servicefaq_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='image',
            new_name='main_image_first',
        ),
        migrations.AddField(
            model_name='service',
            name='main_image_second',
            field=versatileimagefield.fields.VersatileImageField(blank=True, help_text='Main image used on the service inner page (circle and gallery).', null=True, upload_to='service/images'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=versatileimagefield.fields.VersatileImageField(blank=True, help_text='gif image for listing page).', null=True, upload_to='service/icons'),
        ),
    ]
