# Generated by Django 5.2.4 on 2026-01-17 06:34

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_rename_image_service_main_image_first_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.AddField(
            model_name='service',
            name='description1',
            field=tinymce.models.HTMLField(blank=True, help_text='Description 1 for the service Inner page', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description2',
            field=tinymce.models.HTMLField(blank=True, help_text='Description 2 for the service Inner page', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='sub_description',
            field=tinymce.models.HTMLField(blank=True, help_text='Sub description for the service Inner page', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='sub_title',
            field=models.CharField(blank=True, help_text='Sub title for the service Inner page', max_length=100, null=True),
        ),
    ]
