# Generated by Django 5.2.4 on 2026-01-18 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_remove_service_description_service_description1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='works', to='web.service'),
            preserve_default=False,
        ),
    ]
