# Generated by Django 5.2.4 on 2026-01-19 05:29

import django.db.models.deletion
import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_works_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='works',
            name='image',
        ),
        migrations.AddField(
            model_name='works',
            name='icon',
            field=versatileimagefield.fields.VersatileImageField(default=1, help_text='image for listing card', upload_to='works'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='works',
            name='inner_page_main_image',
            field=versatileimagefield.fields.VersatileImageField(default=1, help_text='image for Inner page Main Image', upload_to='works'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='WorksRelatedImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_related_images', versatileimagefield.fields.VersatileImageField(help_text='Add on images for work', upload_to='works')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workImage', to='web.service')),
            ],
        ),
    ]
