# Generated by Django 5.2.4 on 2026-01-19 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_remove_works_image_works_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksrelatedimages',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workImage', to='web.works'),
        ),
    ]
