# Generated by Django 5.2.4 on 2026-01-19 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_alter_worksrelatedimages_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='works',
            name='link',
        ),
    ]
